# Configuración del Pipeline de ML - Smart Logistics
# Proyecto: Automatización con GitHub Actions y MLflow

# Rutas de datos
data:
  raw_data_path: "data/smart_logistics_dataset.csv"
  test_size: 0.2
  random_state: 42
  target_column: "Logistics_Delay"
  
# Columnas a usar en el modelo
features:
  numeric:
    - Latitude
    - Longitude
    - Inventory_Level
    - Temperature
    - Humidity
    - Waiting_Time
    - User_Transaction_Amount
    - User_Purchase_Frequency
    - Asset_Utilization
    - Demand_Forecast
  categorical:
    - Asset_ID
    - Shipment_Status
    - Traffic_Status
  drop:
    - Timestamp
    - Logistics_Delay_Reason
  
# Configuración de preprocesamiento
preprocessing:
  handle_missing: true
  scaling_method: "standard"
  encode_categoricals: true
  
# Configuración del modelo
model:
  type: "RandomForestClassifier"
  params:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 5
    min_samples_leaf: 2
    random_state: 42
    n_jobs: -1
    class_weight: "balanced"
  
# Configuración de MLflow
mlflow:
  experiment_name: "smart_logistics_delay_prediction"
  tracking_uri: "file:./mlruns"
  run_name: "random_forest_v1"
  
# Configuración de métricas a evaluar
metrics:
  - "accuracy"
  - "f1_score"
  - "precision"
  - "recall"
  - "roc_auc"